# Site settings
title: Cheng-Yu (Alan) Chuang
description: Alan's Resume Page
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Cheng-Yu (Alan) Chuang
user_description: Alan Chuang is a highly motivated research assistant at the People and Robots Laboratory (PeRL) in the Department of Computer Science at San Francisco State University. He succeeds in improving the Video Description AI model to be a state-of-the-art one.
user_title: Machine Learning Engineer
email: yueyue0401@gmail.com
# twitter_username: lorem_ipsum
instagram_username: yueyue0401
facebook_username: yueyue0401
linkedin_username: cy-alan-chuang
github_username:  yueyue0401
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src', 'node_modules', 'vendor']

